# Generated by Django 2.0 on 2017-12-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.FloatField(max_length=10)),
                ('x2', models.FloatField()),
                ('r1x1', models.FloatField()),
                ('r1x2', models.FloatField()),
                ('r2x1', models.FloatField()),
                ('r2x2', models.FloatField()),
                ('maxmin', models.CharField(choices=[('Max', 'Max'), ('Min', 'Min')], default='Max', max_length=10)),
                ('maiormenorR1', models.CharField(choices=[('>=', '>='), ('=', '='), ('<=', '=>')], default='>=', max_length=10)),
                ('maiormenorR2', models.CharField(choices=[('>=', '>='), ('=', '='), ('<=', '=>')], default='>=', max_length=10)),
                ('b1', models.FloatField()),
                ('b2', models.FloatField()),
            ],
        ),
    ]
