# Generated by Django 2.0 on 2017-12-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20171220_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplex',
            name='b4',
        ),
        migrations.RemoveField(
            model_name='simplex',
            name='r4x1',
        ),
        migrations.RemoveField(
            model_name='simplex',
            name='r4x2',
        ),
    ]
