# Generated by Django 2.0 on 2018-01-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rx', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='x',
            new_name='x1',
        ),
        migrations.AddField(
            model_name='objetivo',
            name='x2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivo',
            name='x3',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivo',
            name='x4',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivo',
            name='x5',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
