# Generated by Django 2.0 on 2018-01-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180102_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='x1',
            new_name='x',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='x2',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='x3',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='x4',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='x5',
        ),
    ]
