# Generated by Django 2.0 on 2018-01-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20180103_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('O', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
        migrations.DeleteModel(
            name='Restricao',
        ),
    ]
